### ISSUE TITLE
support angular 6

### ISSUE THREAD

**Issue by xmlking** [TradeMe/ng-defer-load#10]
helps to avoid those warnings 
```
$ npm i @trademe/ng-defer-load
npm WARN @trademe/ng-defer-load@1.0.1 requires a peer of @angular/common@^5.2.5 but none is installed. You must install peer dependencies yourself.
npm WARN @trademe/ng-defer-load@1.0.1 requires a peer of @angular/core@^5.2.5 but none is installed. You must install peer dependencies yourself.
npm WARN @trademe/ng-defer-load@1.0.1 requires a peer of @angular/platform-browser@^5.2.5 but none is installed. You must install peer dependencies yourself.
npm WARN @trademe/ng-defer-load@1.0.1 requires a peer of rxjs@^5.5.6 but none is installed. You must install peer dependencies yourself.
```

**Comment by timwickey** [comment]
Cannot use this without updating to Angular 6 asn rxjs has changed substantially. 

`ERROR in ./node_modules/@trademe/ng-defer-load/dist/defer-load.directive.js
Module not found: Error: Can't resolve 'rxjs/observable/fromEvent' in '~node_modules/@trademe/ng-defer-load/dist'`

**Comment by matthewharwood** [comment]
I'm not able to even get this running in Angular v6? any Updates?

**Comment by VamsiVempati** [comment]
A new version v2.0.0 has been released which now supports Angular 6, closing this issue, cheers.
