### ISSUE TITLE
Extend peer dependencies to Angular 7

### ISSUE THREAD

**Issue by stefan-karlsson** [TradeMe/ng-defer-load#21]
### This is a...

* [x] feature request
* [ ] bug report
* [ ] usage question

### What toolchain are you using for transpilation/bundling?

* [x] @angular/cli

### Environment

NodeJS Version: 10.9.0
Typescript Version: 3.1.6
Angular Version: 7.0.3
@trademe/ng-defer-load: 2.0.0
@angular/cli version: 7.0.5
OS: Windows 10

### Expected Behaviour:
No warnings should be shown

### Actual Behaviour:
running `npm install` throws the following warning:

```
npm WARN @trademe/ng-defer-load@2.0.0 requires a peer of @angular/common@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @trademe/ng-defer-load@2.0.0 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @trademe/ng-defer-load@2.0.0 requires a peer of @angular/platform-browser@^6.0.0 but none is installed. You must install peer dependencies yourself.
```

### Additional Notes:
Need to add support for Angular7, there is no big difference between v6 and v7, and package already have support for v6.
We should make sure to update codelyzer package to 4.5.0 to work with Angular 7 too.

**Comment by VamsiVempati** [comment]
New version released for Angular 7 upgrade.
