### ISSUE TITLE
Feature Request - Release this plugin as ES2015 module

### ISSUE THREAD

**Issue by naveedahmed1** [TradeMe/ng-defer-load#39]
When compiling Angular project with latest version of Angular CLI it throws below warning:

`mytest.module.ts depends on @trademe/ng-defer-load. CommonJS or AMD dependencies can cause optimization bailouts.`

Google advises against using CommonJS modules because it can impact the tree-shaking of application as explained here https://web.dev/commonjs-larger-bundles/

I would therefore request you to please release this plugin as es2015 module.

Thank you

**Comment by mzoellner** [comment]
Hi @naveedahmed1 
I have created #40 to address this.
Will push a new npm version as well.

**Comment by naveedahmed1** [comment]
Thank you so much @mzoellner really appreciate :)
