### ISSUE TITLE
Angular 5 - Building issues

### ISSUE THREAD

**Issue by growthengineering** [TradeMe/ng-defer-load#41]
Hello,

We are facing some build issues, any help would be helpful. 

<img width="1300" alt="Screenshot 2020-07-15 at 16 14 41" src="https://user-images.githubusercontent.com/33963575/87563835-99362a00-c6b7-11ea-8935-0912c0f2ff6a.png">

**ionic info** 

`Ionic:

   Ionic CLI          : 6.10.1 (/Users/joaolourenco/.nvm/versions/node/v12.16.2/lib/node_modules/@ionic/cli)
   Ionic Framework    : ionic-angular 3.9.9
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 23 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 1.0.0

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v12.16.2 (/Users/joaolourenco/.nvm/versions/node/v12.16.2/bin/node)
   npm        : 6.14.4
   OS         : macOS Catalina
   Xcode      : Xcode 11.5 Build version 11E608c
`

**angular packages**
with  - "typescript": "2.6.2"

![image](https://user-images.githubusercontent.com/33963575/87564068-dc909880-c6b7-11ea-9ed7-75f0840c9e09.png)

**Comment by alvarorodriguezestruch** [comment]
It happends when you use the last version at this moment of the library (8.2.1) downgrading to version 8.2.0 make it works with Angular 5. The version 8.2.1 breaks build with Angular 5.

I have to say that it only happends to me when using --prod flag

**Comment by NickGeek** [comment]
Hi, hopefully @alvarorodriguezestruch's suggestion worked for you.

We are moving to compile with Ivy, which means that the minimum supported version of Angular will be 12.
