### ISSUE TITLE
Error in Angular 7 production build

### ISSUE THREAD

**Issue by muntaha-techlogicians** [TradeMe/ng-defer-load#44]
Angular version:  7.2.15

Working well in the local. but getting this error, while generating production build. please check and let me know. 
![image](https://user-images.githubusercontent.com/46000696/93755770-ae828400-fc25-11ea-86c4-2ebdf4b48f86.png)

**Comment by NickGeek** [comment]
The minimum version the current version of this library supports is Angular 8, although we recommend Angular 10+. Version v3.1.0 should work for older versions of Angular.
