### ISSUE TITLE
FF 52 loads all content

### ISSUE THREAD

**Issue by motasus** [TradeMe/ng-defer-load#45]
Firefox <= 52 loads all content on current tab and all other tabs in Angular 8 and ng-defer-load v8.2.1. What browsers are supported?

**Comment by NickGeek** [comment]
The code relies on Intersection Observers. A support list is on the MDN page: https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API#browser_compatibility

In terms of Firefox it requires FF55 or higher.
